@extends('client.partials.main')

@section('content')
            <!-- Page Header Start -->
            <div class="container-fluid page-header mb-5 p-0" style="background-image: url({{ asset('assets/img/carousel-1.jpg')}});">
                <div class="container-fluid page-header-inner py-5">
                    <div class="container text-center pb-5">
                        <h1 class="display-3 text-white mb-3 animated slideInDown">Politique et confidentialité</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb justify-content-center text-uppercase">
                                <li class="breadcrumb-item"><a href="/">Accueil</a></li>
                                <li class="breadcrumb-item text-white active" aria-current="page">Politique et confidentialité</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
            <!-- Page Header End -->
    
    
            <!-- About Start -->
            <div class="container-xxl py-5">
                <div class="container">
                    <p>
                        <h6 class="section-title text-start text-primary text-uppercase">Charte de confidentialité et informations sur les cookies</h6>
                        <br><br>
                        <h6 class="section-title text-end text-primary">Charte de confidentialité</h6>
                            <br>
                            18 avr 2023
                            <br>
                            Tout d’abord, nous accordons de l’importance à votre vie privée.<br> Nous savons que cette phrase est souvent mentionnée dans ce type de publication mais nous prenons ce sujet très au sérieux. En utilisant les services de SOHC, vous nous accordez votre confiance, et nous tenons à la préserver. Pour cela, nous mettons tout en œuvre pour protéger et sécuriser vos données personnelles.
                            Ce document («la présente Charte de confidentialité» ou «notre Charte de confidentialité») explique, de façon claire et transparente, comment nous utilisons et traitons vos données personnelles. Il vous informe également des droits que vous pouvez exercer concernant vos données personnelles et vous indique comment nous contacter. Veuillez également consulter le document Informations sur les cookies qui détaille la façon dont SOHC utilise les cookies et d’autres technologies de suivi similaires.
                            Si vous avez déjà utilisé les services de SOHC, vous savez que nous proposons des services en ligne liés à l’immobilier via nos sites Internet, nos applications, ainsi que d’autres plateformes en ligne telles que les sites Internet de nos partenaires ou les réseaux sociaux. Nous tenons à préciser que toutes les informations que vous vous apprêtez à lire ne s’appliquent généralement pas à seulement une ou deux plateformes, mais à l’ensemble d’entre elles.
                            La présente Charte de confidentialité s’applique d’ailleurs à toutes sortes d’informations clients que nous recueillons à travers les plateformes susmentionnées ou par d’autres moyens associés à ces plateformes (par ex. lorsque vous contactez notre Service Clients par e-mail).
                            La présente Charte de confidentialité est susceptible d’être modifiée de temps à autre. Nous vous recommandons donc de consulter cette page régulièrement pour connaître les dernières mises à jour. Si nous apportons des modifications à la présente Charte de confidentialité et que ces dernières vous impactent de manière significative, nous vous en informerons avant le début de toute nouvelle activité.
                            Termes utilisés dans cette Charte de confidentialité
                            <br>« Fournisseur  » désigne un tour-opérateur ou le fournisseur de l’hébergement (par ex. l’hôtel, le motel, l’appartement, la chambre d’hôtes, le propriétaire), de l’attraction (par ex. le parc (à thème), le musée, la visite touristique), du transport (par ex. de la location de voiture, de la croisière, du billet de train, du transfert aéroport, de la visite en bus, du transfert), des assurances de  et de tout autre produit ou service lié au  disponible ponctuellement sur la Plateforme pour une Réservation.
                            <br> « Service de  » désigne le service de commande, d’achat, de paiement (facilité) ou de réservation en ligne des différents produits et services proposés SOHC 
                            <br>« Réservation logement » désigne la commande, l’achat, le paiement ou la réservation d’un logement.
                            <br>
                            <h6 class="section-title text-end text-primary">Pourquoi SOHC recueille-t-elle et utilise-t-elle vos données personnelles ?</h6>
                            <br>
                            Nous ne pouvons pas vous aider à réserver le logement de vos rêves sans que vous nous fournissiez certaines informations. C’est pourquoi nous vous demandons quelques renseignements lorsque vous utilisez nos services. Il s’agit d’informations générales telles que vos nom et prénom, vos coordonnées, vos informations de paiement etc…
                            Nous recueillons également les données provenant de l’ordinateur, du téléphone, de la tablette ou de tout autre appareil que vous utilisez pour accéder à nos services. Cela inclut votre adresse IP, le navigateur que vous utilisez et vos paramètres de langue. Dans certains cas, nous recevons aussi des données vous concernant de la part d’autres sources ou lorsque nous recueillons automatiquement d’autres données.
                            Il s’agit d’un aperçu général, mais si vous souhaitez en savoir plus sur les informations que nous recueillons, vous trouverez plus de renseignements ci-dessous.
                            En savoir plus sur les données personnelles que nous recueillons
                            
                            
                            Nous vous demandons vos informations personnelles pour une bonne raison : vous aider à organiser vos Réservations en ligne, et nous assurer que vous obtenez le meilleur service possible.
                            Nous utilisons également vos données personnelles pour vous informer de nos dernières réductions, de nos offres spéciales et d’autres produits ou services qui, selon nous, pourraient vous intéresser. Il existe d’autres utilisations possibles de vos données personnelles. Lisez la suite pour en savoir plus.
                            En savoir plus sur la collecte de vos données par SOHC 
                            <br>
                            <h6 class="section-title text-end text-primary">Comment vos données sont-elles partagées avec des tiers par SOHC?</h6>
                            
                            <br>
                            Les services proposés par SOHC incluent plusieurs tiers, de différentes façons et pour plusieurs raisons. La raison principale est de partager les données pertinentes avec le Fournisseur afin de finaliser votre Réservation.
                            Nous travaillons également avec d’autres tiers afin de vous faire bénéficier des services de SOHC. Il peut s’agir d’institutions financières, d’annonceurs, de filiales du groupe SOHC et d’autres sociétés qui forment le groupe SOHC. Dans certains cas, si la législation en vigueur l’exige, nous pouvons partager vos données avec des autorités gouvernementales ou autres autorités.
                            Ci-dessous, vous trouverez plus de renseignements sur la façon dont les informations que vous nous communiquez sont utilisées et échangées avec ces tiers.
                            En savoir plus sur la façon dont vos informations sont partagées avec des tiers
                            <br>
                            <h6 class="section-title text-end text-primary">Comment SOHC utilise-t-elle les réseaux sociaux ?</h6>
                            <br>
                            L’utilisation des réseaux sociaux peut être intégrée de plusieurs façons aux services proposés par SOHC. Cela peut comprendre la collecte de certaines de vos données personnelles par nous, ou la réception de certaines de vos informations par le réseau social. Si vous souhaitez plus de renseignements sur la façon dont ces informations sont utilisées et échangées, lisez ce qui suit.
                            En savoir plus sur la façon dont nous utilisons les données recueillies sur les réseaux sociaux
                            Quelles sont les mesures de sécurité et de rétention mises en place par SOHC pour protéger vos données personnelles ?
                            Nous avons mis en place de nombreuses procédures pour empêcher tout accès non autorisé et tout usage abusif des données personnelles que nous traitons.
                            En savoir plus sur les procédures de sécurité et de rétention
                            <br>
                            <h6 class="section-title text-end text-primary">Comment SOHC traite-t-elle les données personnelles relatives aux enfants ?</h6>
                            <br>
                            Sauf disposition contraire, vous devez être âgé(e) d’au moins 17 ans pour pouvoir utiliser les services de SOHC. Les informations sur les enfants ne sont traitées qu’avec le consentement de leurs parents ou de leur tuteur légal, ou lorsque ces renseignements sont partagés avec nous par les parents ou le tuteur légal.
                            En savoir plus sur les données personnelles que nous recueillons sur les enfants de moins de 17 ans
                            <br>
                            <h6 class="section-title text-end text-primary">Pouvez-vous contrôler les données personnelles que vous avez partagées avec SOHC?</h6>
                            <br>
                            Entre autres, vous avez le droit de demander à tout moment à consulter les données personnelles que nous conservons à votre sujet. Vous pouvez demander l’accès à vos données personnelles ou leur suppression en soumettant ce formulaire. Si vous souhaitez en savoir plus sur votre droit de contrôle sur vos données personnelles, lisez ce qui suit.
                            En savoir plus sur la façon dont vous pouvez contrôler vos données personnelles
                            Dispositions par pays
                            Nous pouvons être amenés à fournir des informations supplémentaires en fonction de la législation en vigueur dans le pays dans lequel vous résidez. Vous trouverez, le cas échéant, des informations supplémentaires concernant votre pays ou région ci-dessous.
                            En savoir plus sur les dispositions par pays
                            <br>
                            <h6 class="section-title text-end text-primary">Quels types de données personnelles sont recueillis par SOHC?</h6>
                            <br>
                            Nous comprenons que vous souhaitez plus d’informations à ce sujet. Voici donc plus de détails sur les données que nous collectons.
                            Données personnelles que vous partagez avec nous
                            SOHC recueille et utilise les informations que vous lui fournissez. Lorsque vous effectuez une Réservation , vous devez (au minimum) indiquer vos nom et prénom ainsi que votre adresse e-mail.
                            <br>Selon votre Réservation, il est également possible que nous vous demandions votre adresse postale, votre numéro de téléphone, vos informations de paiement, votre date de naissance, votre emplacement actuel en cas de services à la demande
                            Si vous devez contacter votre Fournisseur par notre biais, échanger avec notre Service Clients ou nous contacter par un autre moyen (par exemple via les réseaux sociaux ou un chatbot), nous recueillerons également vos informations à ce moment-là. Cela peut se produire lorsque vous nous contactez pour nous faire part de votre avis ou nous demander notre aide lors de l’utilisation de nos services.
                            Vous pouvez également être invité(e) à rédiger un commentaire qui permettra aux autres clients d’en savoir plus sur votre expérience lors de l’utilisation de notre site. Lorsque vous rédigez un commentaire sur la plateforme SOHC, nous recueillons toutes les informations que vous renseignez, ainsi que votre nom d’utilisateur et votre avatar, si vous en choisissez un.
                            Vous pouvez également être amené(e) à nous fournir des données à d'autres moments. Par exemple, si vous naviguez sur votre appareil mobile, vous pouvez décider d’autoriser SOHC à voir votre emplacement ou à accéder à certaines coordonnées. Ces informations nous aident à vous proposer les meilleurs services et expériences possibles (par exemple, en vous présentant nos guides sur les villes, en vous suggérant les restaurants ou les attractions les plus proches de votre emplacement ou en vous faisant d’autres recommandations).
                            Si vous créez un compte utilisateur, nous y conserverons vos paramètres personnels, les photos que vous aurez téléchargées et les commentaires que vous aurez rédigés pour vos anciennes réservations. Ces données peuvent être utilisées pour vous aider à planifier et à gérer vos prochaines Réservations, ou encore vous faire bénéficier d’autres fonctionnalités offertes uniquement aux personnes possédant un compte sur notre site (par ex. des avantages ou des récompenses).
                            Vous pouvez également choisir d’ajouter des détails concernant vos pièces d’identité à votre compte. Ainsi, vous n’aurez pas à entrer ces informations à chaque Réservation.
                            Nous pouvons également vous proposer de participer à des programmes de parrainage ou à des tirages au sort pour lesquels vous devez fournir des données personnelles.
                            <br><br>
                            Données personnelles que vous nous donnez sur d'autres personnes
                            Si vous possédez un compte SOHC for Business, vous pouvez également y créer un carnet d’adresses pour planifier et gérer plus facilement les services d’autres clients.
                            Dans certains cas, vous pouvez aussi utiliser SOHC pour partager des informations avec d’autres personnes. Par exemple, vous pouvez partager une liste d’envies, prendre part à une communauté de clients ou participer à des programmes de parrainage, comme expliqué lorsque vous utilisez la fonctionnalité en question.
                            Nous devons souligner ici qu’il est de votre responsabilité de vous assurer que la ou les personnes sur lesquelles vous avez fourni des données personnelles sont au courant de ce fait et qu’elles comprennent et acceptent la façon dont SOHC utilise leurs données (comme expliqué dans la présente Charte de confidentialité).
                            Données personnelles que nous recueillons automatiquement
                            <br><br>
                            Lorsque vous vous rendez sur nos sites Internet ou applications, que vous effectuiez ou non une Réservation, nous collectons automatiquement certaines informations. Il peut s’agir par exemple de votre adresse IP, la date et l’heure de votre connexion à nos services, ainsi que des données sur le matériel informatique et les logiciels de votre ordinateur (tels que le système d’exploitation, le navigateur Internet utilisé, les données relatives à la version du logiciel/de l’application et vos paramètres de langue). Nous recueillons des données sur les clics ainsi que sur les pages que vous avez visitées.
                            Si vous utilisez un appareil mobile, des données identifiant l’appareil, ainsi que des données sur les paramètres et caractéristiques de cet appareil, les crashs de l’application et d’autres activités du système sont également recueillies. Lorsque vous effectuez une Réservation en utilisant ce type d’appareil, notre système enregistre la façon dont vous avez réalisé cette réservation (sur quel site), et/ou quel site Internet vous a redirigé(e) sur le site ou l’application SOHC.
                            Données personnelles que nous recevons d'autres sources
                            Nous ne disposons pas seulement des informations que vous nous donnez. Il est possible que nous recevions également des données vous concernant de la part d’autres sources. Ces autres sources peuvent être des partenaires commerciaux tels que des partenaires affiliés, des filiales du groupe SOHC, ainsi que d’autres tiers indépendants.
                            <br>Tout ce que nous recevons de la part de ces partenaires peut être associé aux informations que vous nous fournissez. Par exemple, les services de Réservations de SOHC ne sont pas uniquement accessibles depuis le site Internet et les applications de SOHC. Ils sont également intégrés aux services de partenaires affiliés que vous trouvez en ligne. Lorsque vous utilisez ces services, il se peut que vous fournissiez les détails de votre réservation à nos partenaires commerciaux qui nous transfèrent ensuite vos données.
                            Nous intégrons également des fournisseurs de services tiers pour faciliter les paiements entre les clients et les Fournisseurs. Ces fournisseurs nous partagent les informations de paiement pour que nous puissions gérer votre Réservation et vous offrir une expérience optimale.
                            Nous recueillons aussi des données lorsque nous recevons une plainte à votre encontre émise par un Fournisseur de, par exemple en cas de comportement inapproprié de votre part.
                            <br> Nous pouvons également recevoir des données sur vous par le biais de services de communication intégrés à nos plateformes. Ces services de communication vous permettent de contacter le Fournisseur auprès duquel vous avez réservé votre hébergement afin que vous puissiez discuter de votre séjour. Dans certains cas, nous recevons des métadonnées à propos de ces communications (par ex. votre identité, l’endroit d’où vous avez appelé ainsi que la date et la durée de l’appel).
                            Il se peut que nous recevions également des informations vous concernant pour vous proposer des publicités plus pertinentes, par exemple des données supplémentaires sur les cookies fournies à SOHC par des réseaux sociaux partenaires. Consultez la section Pourquoi SOHC recueille-t-elle et utilise-t-elle vos données personnelles ? pour en savoir plus.
                            Lorsque vous associez votre compte utilisateur SOHC à votre compte de réseau social, cela peut déclencher un échange de données entre SOHC et le réseau social en question. Vous avez toujours la possibilité de refuser le partage de ces données.
                            Les Fournisseurs peuvent également partager des informations vous concernant avec SOHC. Cela peut par exemple se produire lorsque vous leur posez des questions sur une Réservation en attente, ou si une Réservation a engendré un litige ou un autre problème.

                            <br>
                            <h6 class="section-title text-end text-primary">Pourquoi SOHC recueille-t-elle et utilise-t-elle vos données personnelles ?</h6>
                            <br>
                            Nous utilisons les informations vous concernant pour différents motifs. Vos données personnelles sont susceptibles d'être utilisées dans ces différentes situations :
                            <br>•	Réservations: nous utilisons avant tout vos données personnelles pour finaliser et gérer vos Réservations en ligne – ce qui est essentiel pour que nous puissions vous fournir ce service. Cela comprend l’envoi de communications relatives à votre Réservation, comme les confirmations (y compris la fourniture d’une preuve d’achat ou/et de paiement, le cas échéant), les modifications et les rappels. Dans certains cas, cela peut également inclure le traitement de vos données personnelles, par exemple pour permettre l'enregistrement en ligne auprès du Fournisseur ou le traitement des données personnelles relatives aux éventuels dépôts de garantie.
                            <br>•	Service Clients : nous fournissons un Service Clients dans 02 langues depuis nos bureaux locaux. Nous sommes là pour vous assister 24h/24 et 7j/7. Nous partageons vos données, comme les informations relatives à votre réservation ou à votre compte utilisateur, avec nos équipes internationales du Service Clients pour vous aider lorsque vous avez besoin de nous. Par exemple, il peut s’agir de vous aider à contacter le bon Fournisseur et de répondre aux questions que vous pouvez vous poser à propos de votre Réservation, ou de tout autre chose.
                            <br>•	Fonctionnalités du compte : les utilisateurs de SOHC peuvent créer un compte sur nos sites Internet ou nos applications. Les informations que vous nous fournissez sont utilisées pour gérer ce compte et vous permettre d’effectuer un certain nombre d’actions utiles. Vous pouvez gérer vos Réservation, profiter d’offres spéciales, effectuer facilement vos prochaines Réservations et gérer vos paramètres.
                            Ces paramètres personnels vous permettent de créer et de partager des listes, de partager des photos, de retrouver facilement des Services précédemment consultés et de vérifier d’autres informations que vous avez fournies concernant vos s. Vous pouvez également voir les commentaires que vous avez rédigés sur les établissements dans lesquels vous avez séjourné.
                            Si vous le souhaitez, vous pouvez partager certaines informations de votre compte en créant un profil public associé à votre prénom ou au nom d’utilisateur de votre choix.
                            Si vous possédez un compte SOHC Business, vous pouvez aussi y enregistrer les coordonnées de vos contacts, gérer vos réservations professionnelles et associer les comptes d’autres utilisateurs à ce même compte SOHC Business.
                            <br>•	Groupes en ligne : nous donnons la possibilité aux utilisateurs possédant un compte de rejoindre des groupes en ligne ou des forums (comme les communautés de clientss) sur lesquels ils peuvent échanger.
                            <br>•	Activités marketing : nous utilisons vos données à des fins de marketing. Ces activités comprennent :
                            <br>•	L’utilisation de vos coordonnées pour vous envoyer des informations régulières relatives à des produits et des services de . Vous pouvez vous désabonner de ces communications marketing envoyées par e-mail, facilement et à tout moment. Pour ce faire, il vous suffit de cliquer sur le lien « Se désabonner » que vous trouverez dans toutes nos newsletters et autres communications, ou de gérer vos préférences depuis les paramètres de votre compte.
                            <br>•	Des offres personnalisées, créées à partir de vos informations, peuvent vous être proposées sur le site SOHC, sur ses applications et sur des applications/sites Internet tiers (y compris les réseaux sociaux). Le contenu du site peut également être personnalisé. Il peut s’agir d’offres réservables directement sur SOHC ou sur des sites co-brandés, ou encore d’autres offres ou produits proposés par des tiers qui pourraient vous intéresser.
                            <br>•	Lorsque vous participez à d’autres activités promotionnelles (par ex. à des tirages au sort, à des programmes de parrainage ou à des jeux-concours), seules les informations pertinentes seront utilisées pour la bonne gestion de ces activités.
                            <br>•	Communication avec vous : nous pouvons également vous contacter à d’autres occasions par e-mail, par chatbot, par courrier, par téléphone ou par SMS. Le moyen de communication dépendra des coordonnées que vous avez fournies précédemment.
                            Nous traitons également les communications que vous nous envoyez. Cela peut notamment être le cas pour les raisons suivantes :
                                <br>•	Nous répondons aux/traitons les demandes que vous ou le Fournisseurréservé avez effectuées. SOHC propose également aux clients et aux Fournisseurs de  différents moyens d’échanger via SOHC des informations, des demandes et des commentaires concernant les Fournisseurs de  et les Réservations de  existantes. Pour plus d’informations, consultez la section « Comment SOHC traite-t-elle les communications que vous et votre Fournisseurenvoyez via SOHC SOHC? ».
                                <br>•	Si vous avez commencé votre Réservation en ligne mais ne l’avez pas terminée, nous pouvons vous contacter pour vous inviter à la finaliser. Nous estimons que ce service supplémentaire vous est utile car il vous permet de reprendre là où vous vous étiez arrêté(e), et ce, sans avoir à rechercher un Fournisseurou à remplir une nouvelle fois les détails de votre réservation.
                                <br>•	Lorsque vous utilisez nos services, nous pouvons vous envoyer un questionnaire ou vous inviter à laisser un commentaire sur votre expérience avec SOHC ou avec le Fournisseur de .
                                <br>•	Nous vous envoyons également d’autres informations relatives à vos Réservations de  pour que vous sachiez, par exemple, comment contacter SOHC en cas de besoin lors de votre séjour, ou pour vous aider à préparer et à profiter pleinement de votre . Vous pouvez aussi recevoir des informations sur vos Réservations de  à venir ou un récapitulatif de vos précédentes Réservations de  effectuées sur SOHC.
                                <br>•	Même si vous n’avez aucune Réservation à venir, il se peut que vous receviez d’autres messages à caractère administratif, pouvant inclure des alertes de sécurité.
                                <br>•	En cas de comportement inapproprié, nous pouvons vous envoyer une notification et/ou un avertissement.
                                <br>•	Étude de marché : nous invitons parfois nos clients à participer à des études de marché. Veuillez consulter les informations fournies avec ce type d’invitation afin de comprendre quelles données personnelles seront collectées et comment ces dernières seront utilisées.
                                <br>•	Amélioration de nos services : nous utilisons également les données personnelles à des fins analytiques et pour améliorer nos produits. Nous souhaitons en effet vous proposer de meilleurs services et une expérience utilisateur optimale.
                            Dans ce cas, nous utilisons les données personnelles pour effectuer des tests, résoudre des problèmes et générer des statistiques sur notre activité. Notre but premier est d’obtenir des informations sur la performance de nos services ainsi que sur la façon dont ils sont utilisés, ce qui nous permettra d’optimiser et de personnaliser notre site Internet ainsi que nos applications pour qu’ils soient les plus intuitifs possible. Nous nous efforçons, dans la mesure du possible, d’utiliser des données personnelles anonymisées et dépersonnalisées pour ce travail d’analyse.
                                <br>•	Motifs juridiques : enfin, dans certains cas, nous pouvons utiliser vos données pour traiter et résoudre des actions en justice et des litiges, pour nous conformer à des enquêtes réglementaires ou à la législation en vigueur, pour faire appliquer les conditions d’utilisation du service de réservation en ligne de SOHC ou pour nous conformer aux demandes légales des autorités chargées de l’application de la loi.
                            La communication de vos données personnelles à SOHC est volontaire. Toutefois, il se peut que certains services nécessitent la collecte de certaines données personnelles. Par exemple, nous ne pouvons pas traiter votre Réservation si nous ne recueillons pas votre nom et vos coordonnées.
                            Si nous utilisons des moyens de traitement automatisés des données personnelles qui produisent des effets juridiques ou qui vous affectent de manière significative, nous mettrons toujours en œuvre les mesures nécessaires pour protéger vos droits et vos libertés. Parmi ces droits se trouve le droit d’obtenir une intervention humaine.
                            Pour traiter vos données personnelles telles que mentionnées ci-dessus, nous nous appuyons sur les cadres juridiques suivants :
                            Conformément au cadre juridique applicable, en vue des finalités A et B, SOHC s’appuie sur la base légale qui établit que le traitement des données personnelles est nécessaire à l’exécution d'un contrat, en particulier pour finaliser et gérer votre Réservation.
                            Si les données personnelles requises ne sont pas fournies, SOHC ne peut ni finaliser la Réservation, ni fournir un service clientèle. Compte tenu des finalités C à L, SOHC s’appuie sur ses intérêts légitimes (ou ceux de tiers) pour fournir et améliorer les services et prévenir les fraudes et autres actes illégaux (comme précisé plus en détail dans les points C à L).
                            Lorsque vous utilisez des données personnelles pour servir l’intérêt légitime de SOHC ou d’un tiers, SOHC trouvera toujours un équilibre entre vos droits et vos intérêts concernant la protection de vos données personnelles et les droits et intérêts de SOHC ou ceux du tiers. Pour la finalité M, SOHC s’appuie également, le cas échéant, sur le respect des obligations légales (telles que les demandes d’application de la loi).
                            Enfin, lorsque la loi applicable l’exige, SOHC doit obtenir votre consentement avant de traiter vos données personnelles, y compris pour les campagnes marketing par e-mail ou lorsque la loi en vigueur l’exige.

                            <br>
                            <h6 class="section-title text-end text-primary">Comment SOHC partage-t-elle vos données avec des tiers ?</h6>
                            <br>
                            Dans certains cas, nous serons amenés à partager vos données personnelles avec des tiers. Ces tiers incluent :
                                <br>•	Le Fournisseur via lequel vous avez réservé : Afin de terminer votre Réservation, nous transmettons les détails de la réservation nécessaires au Fournisseur via lequel vous avez réservé. Il s’agit de l’une des choses les plus importantes que nous faisons pour vous.
                            En fonction de la Réservation et du Fournisseur de , les informations que nous partageons peuvent inclure vos nom et prénom, vos coordonnées, vos informations de paiement, le nom de vos compagnons de  et les autres informations ou préférences que vous avez indiquées lors de votre Réservation.
                            Dans certains cas, nous communiquons également au Fournisseur des données supplémentaires sur votre historique. Par exemple, si vous avez déjà réservé auprès de lui, le nombre de réservations que vous avez honorées avec SOHC, la confirmation que nous n’avons reçu aucun signalement de comportement inapproprié vous concernant, le pourcentage de réservations que vous avez annulées dans le passé, ou encore si vous avez déjà rédigé des commentaires sur vos anciens séjours.
                            Si vous avez une question au sujet de votre , nous pouvons contacter le Fournisseur pour traiter votre demande. À moins que le paiement ne soit effectué au cours du processus de réservation sur le site Internet de SOHC, nous transmettrons les coordonnées de votre carte de crédit au Fournisseur auprès duquel vous avez réservé pour un traitement ultérieur du paiement (en supposant que vous nous ayez fourni ces informations).
                            En cas de réclamation ou de litige lié à la Réservation, nous pouvons transmettre vos coordonnées et les informations concernant le processus de réservation au Fournisseur de , afin de permettre le règlement du différend. Cela peut inclure, mais sans s’y limiter, vos adresse e-mail et une copie de votre confirmation de réservation comme preuve qu’une Réservation a été faite ou pour confirmer les raisons de l’annulation.
                            Dans un souci d’exhaustivité, les Fournisseurs de  traiteront également vos données personnelles. SOHC n’a aucun contrôle sur le traitement de ces données. Les Fournisseurs de  peuvent aussi demander des données personnelles supplémentaires, par exemple pour fournir des services supplémentaires ou pour se conformer aux restrictions locales. Si elle est disponible, veuillez consulter la Charte de confidentialité du Fournisseurpour comprendre comment il traite vos données personnelles.
                                <br>•	Fournisseurs de connectivité : veuillez noter que certains Fournisseurs de  peuvent avoir besoin de nous pour partager vos données personnelles avec un Fournisseur de connectivité afin de pouvoir finaliser et gérer votre réservation. Les Fournisseurs de connectivité agissent au nom des Fournisseurs de  et les aident à gérer leurs réservations.
                            Comment SOHC traite-t-elle les communications que vous et le Fournisseur auprès duquel vous avez réservé envoyez via SOHC?
                            SOHC peut vous proposer, à vous et aux Fournisseurs de , différents moyens de communiquer au sujet des Services de  et des Réservations de  existantes, via SOHC. Vous et votre Fournisseur pourrez ainsi contacter SOHC en cas de question sur votre Réservation via le site Internet, nos applications et d’autres canaux.
                            SOHC peut accéder à ces communications et utiliser des systèmes automatisés pour les consulter, les scanner et les analyser pour les raisons suivantes :
                                <br>•	Sécurité
                                <br>•	Prévention des fraudes
                                <br>•	Respect des lois et des réglementations
                                <br>•	Enquête sur de possibles comportements inappropriés
                                <br>•	Développement et amélioration des produits
                                <br>•	Recherche
                                <br>•	Engagement client (notamment dans le but de vous fournir des informations et de vous proposer des offres qui pourraient vous intéresser)
                                <br>•	Service Clients ou assistance technique
                            Nous nous réservons le droit de consulter ou de bloquer la distribution, et ce, à notre seule discrétion, de toute communication qui, selon nous, pourrait contenir du contenu malveillant ou indésirable, ou qui pourrait poser un risque pour vous, les Fournisseurs de  ou d'autres personnes.
                            Toutes les communications envoyées ou reçues par l’intermédiaire des outils de communication de SOHC seront reçues et enregistrées par SOHC. Les Fournisseurs de  et Partenaires commerciaux auprès desquels vous avez effectué une Réservation peuvent également choisir de communiquer avec vous directement par e-mail ou par d’autres canaux non contrôlés par SOHC.

                            Notez que l'utilisation des fonctionnalités des réseaux sociaux peut entraîner l'échange de données personnelles entre SOHC et le fournisseur de services de réseaux sociaux, comme nous le décrivons ci-dessous. Vous êtes libre de ne pas utiliser les fonctionnalités des réseaux sociaux mises à votre disposition.
                                <br>•	Connexion via un compte sur un réseau social. Nous vous offrons la possibilité de vous connecter à votre compte utilisateur SOHC via l’un de vos comptes de réseaux sociaux. Cela vous évite d’avoir à mémoriser plusieurs noms d’utilisateur et mots de passe pour différents services en ligne.
                            Après votre première connexion, vous pourrez utiliser votre compte de réseau social pour vous connecter à votre compte SOHC. Vous pouvez dissocier votre compte utilisateur SOHC de votre compte de réseau social à tout moment.
                                <br>•	Intégration de plug-ins de réseaux sociaux. Nous avons également intégré des plug-ins de réseaux sociaux sur le site Internet et les applications de SOHC. Cela signifie que lorsque vous cliquez ou appuyez sur un des boutons (par exemple le bouton « J’aime » de Facebook), certaines informations sont partagées avec ces réseaux sociaux.
                            Si vous êtes connecté(e) à votre compte de réseau social lorsque vous cliquez ou appuyez sur un de ces boutons, le réseau social peut relier ces informations à votre compte de réseau social. En fonction de vos paramètres, il peut aussi afficher ces actions sur votre profil de réseau social, de façon à ce qu’elles soient visibles par d’autres sur votre réseau.
                                <br>•	Autres services et fonctionnalités de réseaux sociaux. Nous pouvons intégrer d’autres services de réseaux sociaux (comme la messagerie d’un réseau social) pour vous permettre d’interagir avec SOHC ou avec vos contacts concernant nos services.
                            Nous pouvons gérer des comptes de réseaux sociaux et proposer des applications sur plusieurs réseaux sociaux. À chaque fois que vous vous connectez sur SOHC via les réseaux sociaux, votre fournisseur de services de réseaux sociaux peut vous demander de partager des informations avec nous.
                            Si vous acceptez de le faire, le réseau social vous informera généralement de la nature des informations partagées. Par exemple, lorsque vous vous connectez à un compte utilisateur SOHC en utilisant votre compte de réseau social, certaines informations de ce compte peuvent être partagées avec SOHC. Cela inclut votre adresse e-mail, votre âge et les photos de profil que vous avez enregistrées – en fonction des paramètres que vous avez configurés sur votre compte de réseau social.
                            Lorsque vous vous inscrivez sur une application de réseau social SOHC ou que vous vous connectez au service de messagerie d’un réseau social sans compte utilisateur SOHC, les informations que vous choisissez de partager avec nous peuvent inclure les informations de base disponibles dans votre profil de réseau social (y compris votre adresse e-mail, les mises à jour de votre statut et une liste de vos contacts).
                            Nous utiliserons ces informations pour améliorer le service que vous avez demandé, par exemple pour transférer un message que vous souhaitez envoyer à vos contacts, ou pour créer une expérience utilisateur personnalisée sur notre application ou sur nos sites Internet. Cela signifie que si vous le souhaitez, nous pouvons adapter nos services à vos besoins, en vous mettant, vous et vos proches, en contact avec les meilleures destinations de  ainsi qu’en analysant et en améliorant nos services liés aux s.
                            Le réseau social pourra vous en dire plus sur la façon dont il utilise et traite vos données lorsque vous accédez à SOHC via sa plateforme. Cela peut comprendre la manière dont il recoupe vos données personnelles quand vous utilisez SOHC depuis sa plateforme avec les informations qu’il récupère lorsque vous utilisez d’autres plateformes en ligne associées au compte du réseau social.
                            <br>
                            Quelles sont les mesures de sécurité et de rétention mises en place par SOHC pour protéger vos données personnelles ?
                            Nous avons mis en place de nombreuses procédures pour empêcher tout accès non autorisé et tout usage abusif des données personnelles.
                            Afin d'assurer la protection et la confidentialité de vos données personnelles, nous utilisons des procédures et des systèmes professionnels adéquats. Nous appliquons également des procédures de sécurité ainsi que des restrictions techniques et physiques pour limiter l’utilisation et l’accès à vos données personnelles présentes sur nos serveurs. Seul le personnel habilité est autorisé, dans le cadre de son travail, à accéder à vos données personnelles.
                            Nous conserverons vos données personnelles tant que cela est nécessaire pour vous permettre d'utiliser nos services ou pour vous fournir nos services (y compris la gestion de tout compte utilisateur SOHC que vous pouvez posséder), pour nous conformer aux lois applicables, pour résoudre tout litige et pour nous permettre de mener nos activités, y compris afin de détecter et d’éviter toute fraude et/ou toute autre activité illégale. Toutes les données personnelles que nous conservons à votre sujet en tant que client(e) de SOHC sont couvertes par cette Charte de confidentialité.
                            Pour une protection supplémentaire, nous vous recommandons vivement de définir une authentification à deux facteurs pour votre compte utilisateur SOHC. Cela permet d’ajouter une étape d’authentification supplémentaire qui évitera qu’une personne s’étant procuré votre nom d’utilisateur et votre mot de passe (par exemple via l’hameçonnage ou l’ingénierie sociale) puisse se connecter à votre compte. Vous pouvez mettre cela en place dans la section Sécurité des paramètres de votre compte.

                            <br>
                            <h6 class="section-title text-end text-primary">Comment nous contacter ?</h6>
                            <br>
                            Si vous avez la moindre question au sujet de ces Informations sur les cookies, envoyez un e-mail à l’adresse. <b class="text-primary">{{$config->contact_email}}</b>
                            Nos Informations sur les cookies sont susceptibles d’être modifiées de temps à autre. Si ces mises à jour sont importantes, particulièrement pertinentes pour vous ou qu’elles affectent les droits relatifs à la protection de vos données, nous vous contacterons pour vous en faire part. Nous vous recommandons cependant de consulter cette page régulièrement pour vous tenir au courant des dernières mises à jour (moins importantes ou moins pertinentes pour vous).

                    </p>
                </div>
            </div>
            <!-- About End -->
    
@endsection